futures_symbols = [
    "WOOUSDT", "XTZUSDT", "XRPUSDT", "XMRUSDT", "XLMUSDT", "XEMUSDT", "WLDUSDT",
    # 'ZRXUSDT', 'ZILUSDT', 'ZENUSDT', 'ZECUSDT', 'YGGUSDT', 'YFIUSDT', 'XVGUSDT', 'XTZUSDT',
    # 'ZRXUSDT.P', 'ZILUSDT.P', 'ZENUSDT.P', 'ZECUSDT.P', 'YGGUSDT.P', 'YFIUSDT.P', 'XVGUSDT.P', 'XTZUSDT.P',
    # 'XRPUSDT.P', 'XMRUSDT.P', 'XLMUSDT.P', 'XEMUSDT.P', 'WOOUSDT.P', 'WLDUSDT.P', 'WAVESUSDT.P', 'VETUSDT.P',
    # 'UNIUSDT.P', 'UNFIUSDT.P', 'UMAUSDT.P', 'TUSDT.P', 'TRXUSDT.P', 'TRUUSDT.P', 'TRBUSDT.P', 'TOMOUSDT.P',
    # 'TLMUSDT.P', 'THETAUSDT.P', 'SXPUSDT.P', 'SUSHIUSDT.P', 'SUIUSDT.P', 'STXUSDT.P', 'STORJUSDT.P',
    # 'STMXUSDT.P', 'STGUSDT.P', 'SSVUSDT.P', 'SPELLUSDT.P', 'SOLUSDT.P', 'SNXUSDT.P', 'SFPUSDT.P', 'SANDUSDT.P',
    # 'RVNUSDT.P', 'RUNEUSDT.P', 'RSRUSDT.P', 'ROSEUSDT.P', 'RNDRUSDT.P', 'RLCUSDT.P', 'RENUSDT.P', 'REEFUSDT.P',
    # 'RADUSDT.P', 'QTUMUSDT.P', 'QNTUSDT.P', 'PHBUSDT.P', 'PERPUSDT.P', 'PEOPLEUSDT.P', 'OPUSDT.P', 'ONTUSDT.P',
    # 'ONEUSDT.P', 'OMGUSDT.P', 'OGNUSDT.P', 'OCEANUSDT.P', 'NKNUSDT.P', 'NEOUSDT.P', 'NEARUSDT.P', 'MTLUSDT.P',
    # 'MKRUSDT.P', 'MINAUSDT.P', 'MDTUSDT.P', 'MAVUSDT.P', 'MATICUSDT.P', 'MASKUSDT.P', 'MANAUSDT.P', 'MAGICUSDT.P',
    # 'LUNA2USDT.P', 'LTCUSDT.P', 'LRCUSDT.P', 'LQTYUSDT.P', 'LPTUSDT.P', 'LITUSDT.P', 'LINKUSDT.P', 'LINAUSDT.P',
    # 'LEVERUSDT.P', 'LDOUSDT.P', 'KSMUSDT.P', 'KNCUSDT.P', 'KLAYUSDT.P', 'KEYUSDT.P', 'KAVAUSDT.P', 'JOEUSDT.P',
    # 'JASMYUSDT.P', 'IOTXUSDT.P', 'IOTAUSDT.P', 'IOSTUSDT.P', 'INJUSDT.P', 'IMXUSDT.P', 'IDUSDT.P', 'IDEXUSDT.P',
    # 'ICXUSDT.P', 'ICPUSDT.P', 'HOTUSDT.P', 'HOOKUSDT.P', 'HIGHUSDT.P', 'HBARUSDT.P', 'GTCUSDT.P', 'GRTUSDT.P',
    # 'GMXUSDT.P', 'GMTUSDT.P', 'GALUSDT.P', 'GALAUSDT.P', 'FXSUSDT.P', 'FTMUSDT.P', 'FOOTBALLUSDT.P', 'FLOWUSDT.P',
    # 'FLMUSDT.P', 'FILUSDT.P', 'FETUSDT.P', 'ETHUSD.P', 'ETCUSDT.P', 'EOSUSDT.P', 'ENSUSDT.P', 'ENJUSDT.P',
    # 'EGLDUSDT.P', 'EDUUSDT.P', 'DYDXUSDT.P', 'DUSKUSDT.P', 'DOTUSDT.P', 'DOGEUSDT.P', 'DGBUSDT.P', 'DENTUSDT.P',
    # 'DEFIUSDT.P', 'DASHUSDT.P', 'DARUSDT.P', 'CVXUSDT.P', 'CTSIUSDT.P', 'CTKUSDT.P', 'CRVUSDT.P', 'COTIUSDT.P',
    # 'COMPUSDT.P', 'COMBOUSDT.P', 'CKBUSDT.P', 'CHZUSDT.P', 'CHRUSDT.P', 'CFXUSDT.P', 'CELRUSDT.P', 'CELOUSDT.P',
    # 'C98USDT.P', 'BTCUSDT.P', 'BNXUSDT.P', 'BNBUSDT.P', 'BLZUSDT.P', 'BLUEBIRDUSDT.P', 'BLURUSDT.P', 'BCHUSDT.P',
    # 'BATUSDT.P', 'BANDUSDT.P', 'BALUSDT.P', 'BAKEUSDT.P', 'AXSUSDT.P', 'AVAXUSDT.P', 'AUDIOUSDT.P', 'ATOMUSDT.P',
    # 'ATAUSDT.P', 'ASTRUSDT.P', 'ARPAUSDT.P', 'ARBUSDT.P', 'APTUSDT.P', 'API3USDT.P', 'APEUSDT.P', 'ANTUSDT.P',
    # 'ANKRUSDT.P', 'AMBUSDT.P', 'ALPHAUSDT.P', 'ALICEUSDT.P', 'ALGOUSDT.P', 'AGIXUSDT.P', 'ADAUSDT.P', 'ACHUSDT.P',
    # 'AAVEUSDT.P', '1INCHUSDT.P', '1000XECUSDT.P', '1000SHIBUSDT.P', '1000PEPEUSDT.P', '1000LUNCUSDT.P',
    # '1000FLOKIUSDT.P',
]

tokens = ['ETHBTC', 'LTCBTC', 'BNBBTC', 'NEOBTC', 'QTUMETH', 'EOSETH', 'SNTETH', 'BNTETH', 'BCCBTC',
          'GASBTC', 'BNBETH', 'BTCUSDT', 'ETHUSDT', 'HSRBTC', 'OAXETH', 'DNTETH', 'MCOETH', 'ICNETH',
          'MCOBTC', 'WTCBTC', 'WTCETH', 'LRCBTC', 'LRCETH', 'QTUMBTC', 'YOYOBTC', 'OMGBTC', 'OMGETH',
          'ZRXBTC', 'ZRXETH', 'STRATBTC', 'STRATETH', 'SNGLSBTC', 'SNGLSETH', 'BQXBTC', 'BQXETH',
          'KNCBTC', 'KNCETH', 'FUNBTC', 'FUNETH', 'SNMBTC', 'SNMETH', 'NEOETH', 'IOTABTC', 'IOTAETH',
          'LINKBTC', 'LINKETH', 'XVGBTC', 'XVGETH', 'SALTBTC', 'SALTETH', 'MDABTC', 'MDAETH', 'MTLBTC',
          'MTLETH', 'SUBBTC', 'SUBETH', 'EOSBTC', 'SNTBTC', 'ETCETH', 'ETCBTC', 'MTHBTC', 'MTHETH',
          'ENGBTC', 'ENGETH', 'DNTBTC', 'ZECBTC', 'ZECETH', 'BNTBTC', 'ASTBTC', 'ASTETH', 'DASHBTC',
          'DASHETH', 'OAXBTC', 'ICNBTC', 'BTGBTC', 'BTGETH', 'EVXBTC', 'EVXETH', 'REQBTC', 'REQETH',
          'VIBBTC', 'VIBETH', 'HSRETH', 'TRXBTC', 'TRXETH', 'POWRBTC', 'POWRETH', 'ARKBTC', 'ARKETH',
          'YOYOETH', 'XRPBTC', 'XRPETH', 'MODBTC', 'MODETH', 'ENJBTC', 'ENJETH', 'STORJBTC', 'STORJETH',
          'BNBUSDT', 'VENBNB']

tokens_dict = dict(zip(tokens, tokens))


base_url = "wss://fstream.binance.com:443/stream?streams="