version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: crypto_signals
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  parser:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: crypto_signals
      DB_USER: crypto_user
      DB_PASS: crypto_pass
      DB_HOST: db
      DB_PORT: 5432
    command: ["python", "websocket_test_2.py"]

volumes:
  postgres_data:
